services:
  mod-installer:
      image: python:3.13-alpine
      container_name: valheim-mod-installer

      volumes:
        - ./mods:/mods:ro
        - ./config:/config

      working_dir: /mods

      command: python3 update_mods.py

      restart: "no"

  valheim:
    image: ghcr.io/lloesche/valheim-server:latest
    container_name: valheim

    restart: unless-stopped
    stop_grace_period: 2m

    depends_on:
      mod-installer:
        condition: service_completed_successfully

    cap_add:
      - sys_nice

    ports:
      - "2456-2457:2456-2457/udp"

    volumes:
      - ./config:/config
      - ./data:/opt/valheim

    environment:
      SERVER_NAME: "Valheim Local"
      WORLD_NAME: "TestWorld"
      SERVER_PASS: "abc123.."
      SERVER_PUBLIC: "false"

      TZ: "Europe/Madrid"

      # BepInEx
      BEPINEX: "true"

      # Configuración del mundo
      SERVER_ARGS: >-
        -modifier combat veryhard
        -modifier deathpenalty hardcore
        -modifier raids muchless
        -setkey playerevents
        -setkey nomap
        -setkey NoPortals
        -setkey Fire

      # Backups
      BACKUPS: "true"
      BACKUPS_CRON: "0 * * * *"
      BACKUPS_MAX_AGE: "2"

      # Actualizaciones cada hora
      UPDATE_CRON: "0 * * * *"